[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p credentials", "mkdir -p instance"]

[start]
cmd = "bash start_production.sh"
